// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTDJQe21Z9ZZYeWr2YUN4iMYDR1-6bvU',
    appId: '1:1080493782346:web:fe34ba6918622d9997bdb3',
    messagingSenderId: '1080493782346',
    projectId: 'safetytrack-563e5',
    authDomain: 'safetytrack-563e5.firebaseapp.com',
    storageBucket: 'safetytrack-563e5.firebasestorage.app',
    measurementId: 'G-BRH5NHZXHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4jEGwZJjyegVP_GQ-oEjeaykWHqxChxE',
    appId: '1:1080493782346:android:1b0328919101008a97bdb3',
    messagingSenderId: '1080493782346',
    projectId: 'safetytrack-563e5',
    storageBucket: 'safetytrack-563e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeXUR8nUMeVd5jbpE5hkWNaphioMUe1c0',
    appId: '1:1080493782346:ios:957fcee4f969033b97bdb3',
    messagingSenderId: '1080493782346',
    projectId: 'safetytrack-563e5',
    storageBucket: 'safetytrack-563e5.firebasestorage.app',
    iosBundleId: 'com.example.safetytrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeXUR8nUMeVd5jbpE5hkWNaphioMUe1c0',
    appId: '1:1080493782346:ios:957fcee4f969033b97bdb3',
    messagingSenderId: '1080493782346',
    projectId: 'safetytrack-563e5',
    storageBucket: 'safetytrack-563e5.firebasestorage.app',
    iosBundleId: 'com.example.safetytrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsTDJQe21Z9ZZYeWr2YUN4iMYDR1-6bvU',
    appId: '1:1080493782346:web:f51af8fabeedcfb497bdb3',
    messagingSenderId: '1080493782346',
    projectId: 'safetytrack-563e5',
    authDomain: 'safetytrack-563e5.firebaseapp.com',
    storageBucket: 'safetytrack-563e5.firebasestorage.app',
    measurementId: 'G-LYSY75QS36',
  );
}
